# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gao/Desktop/Computer-Orgnization-ARM-/Project/10.CPU_Mem/CPU_Mem.srcs/sources_1/ip/Data_RAM/Data_RAM.xci
# IP: The module: 'Data_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gao/Desktop/Computer-Orgnization-ARM-/Project/10.CPU_Mem/CPU_Mem.gen/sources_1/ip/Data_RAM/Data_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/gao/Desktop/Computer-Orgnization-ARM-/Project/10.CPU_Mem/CPU_Mem.srcs/sources_1/ip/Data_RAM/Data_RAM.xci
# IP: The module: 'Data_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gao/Desktop/Computer-Orgnization-ARM-/Project/10.CPU_Mem/CPU_Mem.gen/sources_1/ip/Data_RAM/Data_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
