# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yanweipeng/Desktop/7.getInsBus/getInsBus.srcs/sources_1/ip/Inst_Rom/Inst_Rom.xci
# IP: The module: 'Inst_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yanweipeng/Desktop/7.getInsBus/getInsBus.gen/sources_1/ip/Inst_Rom/Inst_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_Rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/yanweipeng/Desktop/7.getInsBus/getInsBus.srcs/sources_1/ip/Inst_Rom/Inst_Rom.xci
# IP: The module: 'Inst_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yanweipeng/Desktop/7.getInsBus/getInsBus.gen/sources_1/ip/Inst_Rom/Inst_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
