webtalk_init -webtalk_dir C:/Users/gao/Desktop/Computer-Orgnization-ARM-/Project/10.CPU_Mem/CPU_Mem.sim/sim_1/behav/xsim/xsim.dir/tb_top_CPU_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 17 02:01:32 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "38066e94-8641-4a8e-8197-4fc596b4f619" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "392dccbb94b547a89bd94ee28481a4e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Genuine Intel(R) CPU 0000 @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7248_KB" -context "xsim\\usage"
webtalk_transmit -clientid 254295010 -regid "" -xml C:/Users/gao/Desktop/Computer-Orgnization-ARM-/Project/10.CPU_Mem/CPU_Mem.sim/sim_1/behav/xsim/xsim.dir/tb_top_CPU_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gao/Desktop/Computer-Orgnization-ARM-/Project/10.CPU_Mem/CPU_Mem.sim/sim_1/behav/xsim/xsim.dir/tb_top_CPU_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gao/Desktop/Computer-Orgnization-ARM-/Project/10.CPU_Mem/CPU_Mem.sim/sim_1/behav/xsim/xsim.dir/tb_top_CPU_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
