# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gao/Desktop/ARM-Model/CPU_Mem/CPU_Mem.srcs/sources_1/ip/Inst_ROM/Inst_ROM.xci
# IP: The module: 'Inst_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gao/Desktop/ARM-Model/CPU_Mem/CPU_Mem.gen/sources_1/ip/Inst_ROM/Inst_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/gao/Desktop/ARM-Model/CPU_Mem/CPU_Mem.srcs/sources_1/ip/Inst_ROM/Inst_ROM.xci
# IP: The module: 'Inst_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gao/Desktop/ARM-Model/CPU_Mem/CPU_Mem.gen/sources_1/ip/Inst_ROM/Inst_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
